### ISSUE TITLE
No matching distribution found for tf-nightly-2.0-preview 

### ISSUE THREAD

**Issue by mshahmoh** [ageron/tf2_course#16]
I keep getting `No matching distribution found for tf-nightly-2.0-preview (from -r requirements.txt (line 13))`. Tried it on this Python versions:
3.5.9
  3.6.10
3.6.8
Here's the verbose output of pip install when tried on 3.6.8: 

```
(py368_tf2course) ➜  tf2_course git:(master) pip3 install tf-nightly-2.0-preview==2.0.0.dev20190909 debug --verbose
Created temporary directory: /private/var/folders/82/dztv695d6lgb4tg_lhpl7hjc0000gp/T/pip-ephem-wheel-cache-ol8xrquy
Created temporary directory: /private/var/folders/82/dztv695d6lgb4tg_lhpl7hjc0000gp/T/pip-req-tracker-jtf_htjg
Created requirements tracker '/private/var/folders/82/dztv695d6lgb4tg_lhpl7hjc0000gp/T/pip-req-tracker-jtf_htjg'
Created temporary directory: /private/var/folders/82/dztv695d6lgb4tg_lhpl7hjc0000gp/T/pip-install-njz442no
Collecting tf-nightly-2.0-preview==2.0.0.dev20190909
  1 location(s) to search for versions of tf-nightly-2.0-preview:
  * https://pypi.org/simple/tf-nightly-2-0-preview/
  Getting page https://pypi.org/simple/tf-nightly-2-0-preview/
  Looking up "https://pypi.org/simple/tf-nightly-2-0-preview/" in the cache
  Request header has "max_age" as 0, cache bypassed
  Starting new HTTPS connection (1): pypi.org:443
  https://pypi.org:443 "GET /simple/tf-nightly-2-0-preview/ HTTP/1.1" 404 13
  Status code 404 not in (200, 203, 300, 301)
  Could not fetch URL https://pypi.org/simple/tf-nightly-2-0-preview/: 404 Client Error: Not Found for url: https://pypi.org/simple/tf-nightly-2-0-preview/ - skipping
  Could not find a version that satisfies the requirement tf-nightly-2.0-preview==2.0.0.dev20190909 (from versions: )
Cleaning up...
Removed build tracker '/private/var/folders/82/dztv695d6lgb4tg_lhpl7hjc0000gp/T/pip-req-tracker-jtf_htjg'
No matching distribution found for tf-nightly-2.0-preview==2.0.0.dev20190909
Exception information:
Traceback (most recent call last):
  File "/Users/mohammad.shahmohamma/.pyenv/versions/3.6.8/envs/py368_tf2course/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 143, in main
    status = self.run(options, args)
  File "/Users/mohammad.shahmohamma/.pyenv/versions/3.6.8/envs/py368_tf2course/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 318, in run
    resolver.resolve(requirement_set)
  File "/Users/mohammad.shahmohamma/.pyenv/versions/3.6.8/envs/py368_tf2course/lib/python3.6/site-packages/pip/_internal/resolve.py", line 102, in resolve
    self._resolve_one(requirement_set, req)
  File "/Users/mohammad.shahmohamma/.pyenv/versions/3.6.8/envs/py368_tf2course/lib/python3.6/site-packages/pip/_internal/resolve.py", line 256, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/Users/mohammad.shahmohamma/.pyenv/versions/3.6.8/envs/py368_tf2course/lib/python3.6/site-packages/pip/_internal/resolve.py", line 209, in _get_abstract_dist_for
    self.require_hashes
  File "/Users/mohammad.shahmohamma/.pyenv/versions/3.6.8/envs/py368_tf2course/lib/python3.6/site-packages/pip/_internal/operations/prepare.py", line 218, in prepare_linked_requirement
    req.populate_link(finder, upgrade_allowed, require_hashes)
  File "/Users/mohammad.shahmohamma/.pyenv/versions/3.6.8/envs/py368_tf2course/lib/python3.6/site-packages/pip/_internal/req/req_install.py", line 164, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/Users/mohammad.shahmohamma/.pyenv/versions/3.6.8/envs/py368_tf2course/lib/python3.6/site-packages/pip/_internal/index.py", line 621, in find_requirement
    'No matching distribution found for %s' % req
pip._internal.exceptions.DistributionNotFound: No matching distribution found for tf-nightly-2.0-preview==2.0.0.dev20190909
You are using pip version 18.1, however version 20.2b1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by ageron** [comment]
Thanks for your message. I updated `requirements.txt`, it was outdated. It should be good now.
